# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
    ]
