# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_message_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='position',
            new_name='location',
        ),
    ]
