# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0005_auto_20160608_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='positive', max_length=100),
        ),
    ]
